
server:
  port: 8081

spring:
  application:
    name: "auth-service"  
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: myVerySecretKeyForAuthService1234567890
  expiration: 3600000 # 1h (ms)

